GET http://localhost/pc-shop/api/v0/products/103/photos/
###

GET http://localhost/pc-shop/api/v0/products/103/photos/706
###

POST http://localhost/pc-shop/api/v0/products/103/photos/
content-type: application/json

{"uri":"0000000.jpg"}
###

PATCH http://localhost/pc-shop/api/v0/products/103/photos/706
content-type: application/json

{"uri":"0x0x0x0.jpg"}
###

DELETE http://localhost/pc-shop/api/v0/products/103/photos/706
###
