GET http://localhost/pc-shop/api/v0/customers/101/recomend/
cookie: session=ff0099aa
###

GET http://localhost/pc-shop/api/v0/customers/101/recomend/42
cookie: session=ff0099aa
###

POST http://localhost/pc-shop/api/v0/customers/101/recomend/
cookie: session=ff0099aa
content-type: application/json

{"productId":65}
###

PATCH http://localhost/pc-shop/api/v0/customers/101/recomend/42
cookie: session=ff0099aa
content-type: application/json

{"productId":65}
###

DELETE http://localhost/pc-shop/api/v0/customers/101/recomend/42
cookie: session=ff0099aa
###
